name: "k8s toolbox"
description: "A suite of common tools for k8s usage"
inputs:
  kubectl:
    description: "Version of kubectl to use"
    required: false
    default: "v1.18.0"
  kube-config:
    description: "Base 64 encoded ~/.kube/config for kubectl"
    required: true
  kops:
    description: "Version of kops to use"
    required: false
    default: "v1.18.0"
  helm:
    description: "Version of helm to use"
    required: false
    default: "v3.3.4"
  render:
    description: "Version of render to use"
    required: false
    default: "v0.2.0"
  aws-iam-authenticator:
    description: "Version of aws iam authenticator to use"
    required: false
    default: "1.12.10/2019-08-14"
  argo:
    description: "Version of argo to use"
    required: false
    default: "v2.4.3"
runs:
  using: "composite"
  steps:
    - name: kubetcl
      run: |
        sudo curl --fail -sL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${{ inputs.kubectl }}/bin/linux/amd64/kubectl
        sudo chmod +x /usr/local/bin/kubectl
        mkdir -p $HOME/.kube
        echo "${{ inputs.kube-config }}" | base64 -d > $HOME/.kube/config
      shell: bash
    - name: kops
      run: |
        sudo curl --fail -sL -o /usr/local/bin/kops https://github.com/kubernetes/kops/releases/download/${{ inputs.kops }}/kops-linux-amd64
        sudo chmod +x /usr/local/bin/kops
      shell: bash
    - name: helm
      run: |
        wget -q https://get.helm.sh/helm-${{ inputs.helm }}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > $HOME/helm 
        sudo mv $HOME/helm /usr/local/bin/helm
        sudo chmod +x /usr/local/bin/helm
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        helm repo update
      shell: bash
    - name: render
      run: |
        sudo curl --fail -sL -o /usr/local/bin/render https://github.com/VirtusLab/render/releases/download/${{ inputs.render }}/render-linux-amd64
        sudo chmod +x /usr/local/bin/render
      shell: bash
    - name: aws iam authenticator
      run: |
        sudo curl --fail -sL -o /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/${{ inputs.aws-iam-authenticator }}/bin/linux/amd64/aws-iam-authenticator
        sudo chmod +x /usr/local/bin/aws-iam-authenticator
      shell: bash
    - name: argo
      run: |
        sudo curl --fail -sL -o /usr/local/bin/argo https://github.com/argoproj/argo/releases/download/${{ inputs.argo }}/argo-linux-amd64
        sudo chmod +x /usr/local/bin/argo
      shell: bash
